apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
  - port: {{ .Values.frontend.servicePort }}
  selector:
    app: azure-vote-front